version: 0.2

phases:
  pre_build:
    commands:
      - cd client
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id ELDLIEI2EXKSO --paths '/*'

artifacts:
  files:
    - '**/*'
  base-directory: client/build
